#!/bin/bash

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Guía: Configurar Codemagic para generar IPA             ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📱 PASO 1: Crear cuenta en Codemagic"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Ir a: https://codemagic.io/signup"
echo "2. Sign up con tu cuenta de GitHub"
echo "3. Autorizar Codemagic a acceder a tus repos"
echo ""
read -p "✓ Presiona ENTER cuando hayas creado la cuenta..."
echo ""

echo "📱 PASO 2: Conectar repositorio"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. En Codemagic, click 'Add application'"
echo "2. Seleccionar 'GitHub'"
echo "3. Buscar tu repo (ejemplo: nequix-ios)"
echo "4. Click 'Select'"
echo ""
read -p "✓ Presiona ENTER cuando hayas conectado el repo..."
echo ""

echo "📱 PASO 3: Configurar Apple Developer"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  IMPORTANTE: Necesitas Cuenta Apple Developer (\$99/año)"
echo ""
echo "1. En Codemagic → Teams → [Tu team] → Integrations"
echo "2. Click 'Apple Developer Portal'"
echo "3. Agregar tus credenciales de Apple Developer"
echo "4. Generar certificado de firma"
echo ""
echo "Opciones:"
echo "  a) Dejar que Codemagic genere certificados (recomendado)"
echo "  b) Subir certificados existentes"
echo ""
read -p "✓ Presiona ENTER cuando hayas configurado..."
echo ""

echo "📱 PASO 4: Configurar Build"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. En tu app, click 'Start new build'"
echo "2. Seleccionar workflow: 'ios-release'"
echo "3. Click 'Start new build'"
echo ""
echo "El build toma ~15-20 minutos la primera vez"
echo ""
read -p "✓ Presiona ENTER para ver costos..."
echo ""

echo "💰 COSTOS DE CODEMAGIC"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Plan Free:"
echo "  • 500 minutos/mes gratis (macOS M1)"
echo "  • ~25 minutos por build iOS"
echo "  • = ~20 builds gratis/mes"
echo ""
echo "Plan Pro:"
echo "  • \$40/mes"
echo "  • Minutos ilimitados"
echo ""
echo "Cuenta Apple Developer:"
echo "  • \$99/año (OBLIGATORIO para iOS)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📱 PASO 5: Descargar IPA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Cuando el build termine:"
echo "1. Click en el build"
echo "2. Tab 'Artifacts'"
echo "3. Descargar el archivo .ipa"
echo ""
echo "¡Listo! Ya tienes tu IPA de iOS"
echo ""

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  ✅ Configuración completa                                ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "URLs útiles:"
echo "• Codemagic: https://codemagic.io"
echo "• Apple Developer: https://developer.apple.com"
echo "• Docs Codemagic: https://docs.codemagic.io/yaml-quick-start/building-a-native-ios-app/"
echo ""
